--These are example queries to be used in sqlite3 files generated by the python scripts
-- Specific to survey data version 3

-- all surveys in DB
SELECT * FROM surveys;


-- station information
select distinct sta.sourceAddr "Station MAC",
	   sta.destAddr "Dest MAC",
	   sta.channel "CH",
	   sta.subtype "Data Subtype",
	   sta.surveyInx "Survey",
	   mv.vendorName "OUI Mfg"
from wifi_data sta
left join mac_vendor mv on mv.prefix like substr(sta.sourceAddr, 1, 8)
order by sta.subtype, sta.sourceAddr;


-- station count and unique mac address (with vendor name if applicable)
select distinct count(sta.sourceAddr), sta.sourceAddr, mv.vendorName
from wifi_data sta
left join mac_vendor mv on substr(sta.sourceAddr, 1, 8) like mv.prefix
group by sta.sourceAddr
order by count(sta.sourceAddr) desc;


-- management frame information
select distinct mg.ssid "SSID",
		mg.bssid "BSSID",
		mg.subtype "Management Subtype",
		mv.vendorName "OUI Mfg"
from wifi_management mg
left join mac_vendor mv on mv.prefix like substr(mg.bssid, 1, 8)
where mg.subtype != 'probe request'
order by mg.ssid, mg.bssid, mg.subtype;


-- management count and unique mac address (with vendor name if applicable)
select distinct count(mg.bssid), mg.bssid, mv.vendorName
from wifi_management mg
left join mac_vendor mv on substr(mg.bssid, 1, 8) like mv.prefix
group by mg.bssid
order by count(mg.bssid) desc;


-- stations attached to access points
select distinct
		ap.ssid "AP SSID",
		ap.bssid "AP BSSID",
		sta.sourceAddr "station MAC",
		sta.subtype "station data subtype",
		sta.channel "CH",
		sta.surveyInx "survey",
		mv.vendorName "station vendor"
from wifi_data sta
join wifi_management ap on ap.bssid = sta.destAddr  and ap.surveyInx = sta.surveyInx
left join mac_vendor mv on mv.prefix like substr(sta.sourceAddr, 1, 8)
order by ap.ssid;


-- all distinct bluetooth beacons with vendor, uuid, and survey data
select distinct s.dateTime, s.longitude, s.lattitude, b.name, b.mac, b.rssi, bu.uuidHex, bu.name, u16.uuid16, u32.uuid32, u128.uuid128
from btle b
	join surveys s on s.surveyInx = b.surveyInx
	left join uuid16 u16 on b.btInx = u16.btInx
	left join uuid32 u32 on b.btInx = u32.btInx
	left join uuid128 u128 on b.btInx = u128.btInx
	left join bluetooth_uuids bu on u16.uuid16 = bu.uuidDec
order by bu.name DESC, b.name desc, b.rssi desc, b.name DESC, b.mac;


-- bluetooth count and unique mac address (with vendor name if applicable)
select distinct count(b.mac), b.mac, mv.vendorName
from btle b
	left join mac_vendor mv on substr(b.mac, 1, 8) like mv.prefix
group by b.mac
order by count(b.mac) desc;
